#!/usr/bin/python3
"""Apply a shell command in parallel by using a multiprocessing.pool."""
import configparser
import subprocess
import sys
import time
from copy import copy
from multiprocessing import Pool, cpu_count
from pathlib import Path

_REQUIRED_NUMBER_OR_ARGS = 3

def _get_configuration() -> dict:
    """Get configuration parameters from papply.ini.

    This file can be locate either in the current directory or the user home
    """
    config = configparser.ConfigParser()
    if config.read([Path("./papply.ini"), Path("~/papply.ini").expanduser()]):
        default = config["papply"]
        num_cores = default.getint("num_cores", cpu_count())
        overcommit_factor = default.getint("overcommit_factor", 1)
        show_progress = default.get("show_progress", "iflong")
        long_duration = default.getint("long_duration", 60)
    else:
        num_cores = cpu_count()
        overcommit_factor = 1
        show_progress = "iflong"
        long_duration = 60

    # want to disable progress indication?
    bool_show_progress = show_progress.lower() in ["n", "no", "0", "false"]

    # want to always enable progress indication?
    if show_progress.lower() in ["y", "yes", "1", "true"]:
        long_duration = 0

    return {
        "num_threads": num_cores * overcommit_factor,
        "show_progress": bool_show_progress,
        "long_duration": long_duration,
    }


def _get_variables_from_argument(argument: str) -> list[tuple[str, str]]:
    """Extract variables (directory, name,  extension) from the argument."""
    argument_path = Path(argument)
    return [
        ("%F", argument),
        ("%d", str(argument_path.parents[0])),
        ("%f", str(argument_path.name)),
        ("%n", str(argument_path.stem)),
        ("%e", str(argument_path.suffixes[-1])),
        ("%z", ""),
    ]


def _papply_one(argument: str) -> None:
    """Apply the command to one argument."""
    # the original command passed on the command line
    command = sys.argv[1]

    command_expanded = copy(command)
    # replace special strings with values
    for template, value in _get_variables_from_argument(argument):
        command_expanded = command_expanded.replace(template, value)

    # if the command is not expanded add the argument to the basic command
    # otherwise assume that the command_expanded is complete
    if command_expanded == command:
        command_expanded = f'{command} "{argument}"'

    try:
        reply = subprocess.check_output(
            command_expanded,
            universal_newlines=True,
            shell=True,
            stderr=subprocess.DEVNULL,
        )
        # if there was output to stdout print it here
        if reply:
            print(reply.rstrip("\r\n"))
    except subprocess.CalledProcessError:
        # something went wrong inform the user
        print(f'"{command_expanded}" did not succeed')


def papply_main() -> None:
    """Execute the main logic of papply. It creates the multiprocessing pool."""
    if len(sys.argv) < _REQUIRED_NUMBER_OR_ARGS:
        print('Usage: papply "some command with arguments" files')
        print('Example: papply "gzip -9" *.ps')
        print()
        print("The following variables can used in the command:")
        print(" %F: Full original input")
        print(" %d: directory name (no trailing slash)")
        print(" %f: file name with extension")
        print(" %n: file name without extension")
        print(" %e: extension (with leading .)")
        print(" %z: empty string")
        print()
        print('Example: papply "convert -set colorspace Gray %F %n_gray.jpg" *.ps')
        sys.exit()

    # sys.argv[1] is the command line to call in parallel
    # anything after sys.argv[1] are arguments to this command line
    arguments = sys.argv[2:]
    narguments = len(arguments)

    config_values = _get_configuration()

    pool = Pool(config_values["num_threads"])
    res = pool.imap(_papply_one, arguments)

    if config_values["show_progress"]:
        # register when we start the pool
        start_time = time.monotonic()
        long_running = False
        long_duration = config_values["long_duration"]

        # iteration number that corresponds to
        # 10, 20, .., 90 step in progress
        progress_marks = [round(x/100.0*narguments) for x in range(10, 100, 10)]

        # Loop over the number of arguments to track the progress
        for i in range(narguments):

            # this continues when the iterated map has given the next result
            res.next()

            # when this starts to be a long running process print percentage
            # (10%) progress
            if long_running:
                if i in progress_marks:
                    print(f"PAPPLY: {i} of {narguments} commands executed")
                continue

            # check to see if it is long running
            long_running = time.monotonic() - start_time > long_duration

    pool.close()
    pool.join()


if __name__ == "__main__":
    papply_main()
